### ISSUE TITLE
DataProcessing.py TypeError

### ISSUE THREAD

**Issue by borshago** [LiuzLab/PolyA-miner#2]
Hi,

Running PolyA-miner.py with the arguments -d, -o, -pa, -index, -bed, -c1, -c2, and -fasta, using my own test data, produces the following error:

Traceback (most recent call last):
  File "PolyA-miner-master/PolyA-miner.py", line 231, in <module>
    main()
  File "PolyA-miner-master/PolyA-miner.py", line 129, in main
    if DataProcessing.DataProcessing(args.d, args.o, args.p, args.index, controls, treated, args.key, lf) == 1:
  File "PolyA-miner-master/lib/DataProcessing.py", line 49, in DataProcessing
    process_rawfastq(d, s, np)
  File "PolyA-miner-master/lib/DataProcessing.py", line 7, in process_rawfastq
    cmd = 'fastp -i ' + s + ' -a AGATCGGAAGAGC -f 6 -g -l 40 -h ' + d + '/' + d.split('/')[-1] + '_trim-report.html -w ' + mc + ' -Q -o ' + d + '/' + d.split('/')[-1] + '_trim.fastq'
TypeError: must be str, not int

This is solved by making the following change in line 7 of DataProcessing.py:

mc -> str(mc)

Best,
Daniel

**Comment by hari-yalamanchili** [comment]
Hi Daniel,

Thank you for raising this! 

Best,
Hari
