### ISSUE TITLE
Problem using the `-expNovel` flag. 

### ISSUE THREAD

**Issue by sopenaml** [LiuzLab/PolyA-miner#6]
I can run the tool without the flat and I get Results, but if I use the `-expNovel` flag I get the error below.
```
Traceback (most recent call last):
  File "/camp/apps/eb/dev/software/PolyA-miner/5af2bae-GCC-8.3.0-no-OFED/PolyA-miner.py", line 234, in <module>
    main()
  File "/camp/apps/eb/dev/software/PolyA-miner/5af2bae-GCC-8.3.0-no-OFED/PolyA-miner.py", line 151, in main
    if ExtNovelAPA.ExtNovelAPA(args.o, args.key, args.pa, args.bed, args.fasta, args.apaBlock, args.mdapa, args.md, args.anchor, args.ip, args.p, lf) == 1:
  File "/camp/apps/eb/dev/software/PolyA-miner/5af2bae-GCC-8.3.0-no-OFED/lib/ExtNovelAPA.py", line 157, in ExtNovelAPA
    df = df[df.Distance >= -16000]
  File "/camp/home/sopenam/.local/lib/python3.9/site-packages/pandas/core/ops/common.py", line 69, in new_method
    return method(self, other)
  File "/camp/home/sopenam/.local/lib/python3.9/site-packages/pandas/core/arraylike.py", line 52, in __ge__
    return self._cmp_method(other, operator.ge)
  File "/camp/home/sopenam/.local/lib/python3.9/site-packages/pandas/core/series.py", line 5502, in _cmp_method
    res_values = ops.comparison_op(lvalues, rvalues, op)
  File "/camp/home/sopenam/.local/lib/python3.9/site-packages/pandas/core/ops/array_ops.py", line 284, in comparison_op
    res_values = comp_method_OBJECT_ARRAY(op, lvalues, rvalues)
  File "/camp/home/sopenam/.local/lib/python3.9/site-packages/pandas/core/ops/array_ops.py", line 73, in comp_method_OBJECT_ARRAY
    result = libops.scalar_compare(x.ravel(), y, op)
  File "pandas/_libs/ops.pyx", line 107, in pandas._libs.ops.scalar_compare
TypeError: '>=' not supported between instances of 'str' and 'int'

```

**Comment by hari-yalamanchili** [comment]
Fixed in v1.1. Tested with fastp v0.20.0, bedtools v2.27.1, bowtie2 v2.3.5.1, samtools v1.10, featureCounts v2.03.
Thanks!
