### ISSUE TITLE
ExtractPolyAsites.py  Bedtools merge error (v29.1)

### ISSUE THREAD

**Issue by anthonycaputo852** [LiuzLab/PolyA-miner#9]
I'm running PolyAminer in fastq mode and I get the following error: 

concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/process.py", line 261, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/process.py", line 210, in _process_chunk
    return [fn(*args) for args in chunk]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/process.py", line 210, in <listcomp>
    return [fn(*args) for args in chunk]
            ^^^^^^^^^
  File "/Users/anthonycaputo/Desktop/Schaffer_Data/bioinformatics/polyAminer/ExtractPolyAsites.py", line 85, in mergeBG
    merged = bed.merge(s=True,c=[6], o='distinct') # For bedtools 2.29
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anthonycaputo/.local/share/virtualenvs/polyAminer-sgOz7MNh/lib/python3.11/site-packages/pybedtools/bedtool.py", line 909, in decorated
    result = method(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anthonycaputo/.local/share/virtualenvs/polyAminer-sgOz7MNh/lib/python3.11/site-packages/pybedtools/bedtool.py", line 388, in wrapped
    stream = call_bedtools(
             ^^^^^^^^^^^^^^
  File "/Users/anthonycaputo/.local/share/virtualenvs/polyAminer-sgOz7MNh/lib/python3.11/site-packages/pybedtools/helpers.py", line 460, in call_bedtools
    raise BEDToolsError(subprocess.list2cmdline(cmds), stderr)
pybedtools.helpers.BEDToolsError: 
Command was:

	bedtools merge -s -o distinct -i /var/folders/80/_7n8_jhd0cddgbvjdxb_zmlw0000gn/T/pybedtools.cx8vq8sw.tmp -c 6

Error message was:

*****
***** ERROR: Requested column 6, but database file /var/folders/80/_7n8_jhd0cddgbvjdxb_zmlw0000gn/T/pybedtools.cx8vq8sw.tmp only has fields 1 - 0.

I initially ran the program on the most recent version of bedtools  (v2.31), but then I saw in the ExtractPolyAsites.py script there were comments indicating that some old code was compatible with bedtools v26, but then updated to work with bedtools v29. So I switched from v31 to 29 but am still experincing the same issue. Any feedback or direction would be greatly appreciated.

**Comment by anthonycaputo852** [comment]
I want to add that this error only occurs when I set -Novel to a value of 1. It does not occur when -Novel is 0
